# Generated by Django 4.1.5 on 2023-01-15 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DollarRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('order_number', models.IntegerField(default='0', unique=True)),
                ('cost_usd', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('cost_uah', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('delivery_time', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
